server:
  port: 9000
  servlet:

    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://frontdoor.cuqx7qysunul.ap-northeast-2.rds.amazonaws.com/frontdoorprivacy
    username: admin
    password: 11yhchoa04
  mail:
    host: smtp.naver.com
    port: 465
#    username: 니네 네이버 아이디 네이버 인증기능 구현 설정 따로 해줘야하니 하고 할것  t시팔련아 pussy
#    password: 니네 네이버 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com


mybatis:
  type-aliases-package: frontdoorprivacy.model
  mapper-locations: mapper/*/*.xml