server:
  port: 8080
  servlet:

    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frontdoor?serverTimezone=Asia/Seoul
    username: root
    password: wldhks0107

mybatis:
  type-aliases-package: frontdoorprivacy.model
  mapper-locations: mapper/*/*.xml