server:
  port: 8080
  servlet:

    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frontdoor?serverTimezone=Asia/Seoul
    # jdbc:mysql://f1456e6f-446e-42cd-a559-7ab21392c3ca.external.kr1.mysql.rds.nhncloudservice.com/frontdoor
    username: root
    password:
  mail:
    host: smtp.naver.com
    port: 465
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com


mybatis:
  type-aliases-package: frontdoorprivacy.model
  mapper-locations: mapper/*/*.xml